CREATE TABLE DONATION(

FIRST_NAME VARCHAR(55) NOT NULL,
LAST_NAME VARCHAR(55) NOT NULL,
EMAIL_ADDRESS VARCHAR(55) NOT NULL,
PHONE_NUMBER VARCHAR(55) NOT NULL,
DONOR_COMMENT VARCHAR(150) NOT NULL,
DONATION_AMOUNT VARCHAR(55) NOT NULL,
DATE_OF_DONATION VARCHAR(55) NOT NULL,
PAYMENT_METHOD VARCHAR(55) NOT NULL
)